### ISSUE TITLE
[BUG] BLAKE3 error on files larger than 2GB

### ISSUE THREAD

**Issue by ArK-z1** [samuel-lucas6/Milva#3]
Version:
Milva v1.4.0

OS: Windows 10 21H2

test1.xyz size: 2,00 GB (2.147.483.648 bytes)

Error:
```
milva --blake3 test1.xyz
test1.xyz - Error: System.IO.IOException

**Comment by samuel-lucas6** [comment]
Thanks for reporting this. I believe the same thing was reported [here](https://github.com/samuel-lucas6/Milva/issues/1#issuecomment-811061696).

I'm still not sure what I can do given it sounds like an upstream issue. The official BLAKE3 implementation will be the most optimised, and C# BouncyCastle doesn't support it.

**Comment by ArK-z1** [comment]
Thanks. I didn't check on the closed issues, so I didn't notice about the upstream issue.

**Comment by samuel-lucas6** [comment]
After proper investigation, this is just me using [Blake3.NET](https://github.com/xoofx/Blake3.NET) wrong 🤦‍♂️ This will be fixed in the next version, so thanks again.

**Comment by sergeevabc** [comment]
Hey, @samuel-lucas6. I'm glad you found the strength to step over the 'talk to the upstream' excuse and review your code. Indeed, there are no more disasters [reported](https://github.com/samuel-lucas6/Milva/issues/1#issuecomment-811061696) back in 2021. Alas, believe it or not, the original [b3sum](https://github.com/BLAKE3-team/BLAKE3/issues/78#issuecomment-801425510) by @oconnor663 STILL sucks.

P.S. Thanks for choosing .NET 6 over 7, so Milva works fine on Windows 7, which my comrades and I will continue to use in the foreseeable future. Happy New 2024 Year!
